version: '3'

services:
    koto:
        image: ghcr.io/jurienhamaker/koto:main
        restart: unless-stopped
        tty: true
        env_file:
            - ./.env
            - ./koto.env
        environment:
            - 'DATABASE_URL=$KOTO_DATABASE_URL'
            - 'INVITE_LINK=$KOTO_INVITE_LINK'
            - 'DISCORD_TOKEN=$KOTO_DISCORD_TOKEN'
            - 'SENTRY_DNS=$KOTO_SENTRY_DNS'
            - 'CLIENT_ID=$KOTO_CLIENT_ID'
            - 'TOP_GG_TOKEN=$KOTO_TOP_GG_TOKEN'
            - 'TOP_GG_VOTE_LINK=$KOTO_TOP_GG_VOTE_LINK'
            - 'DISCORDBOTLIST_TOKEN=$KOTO_DISCORDBOTLIST_TOKEN'
            - 'DISCORDBOTLIST_VOTE_LINK=$KOTO_DISCORDBOTLIST_VOTE_LINK'
            - 'BOTS_GG_TOKEN=$KOTO_BOTS_GG_TOKEN'
            - 'BOTS_GG_VOTE_LINK=$KOTO_BOTS_GG_VOTE_LINK'
        ports:
            - '$EXPOSED_KOTO_API_PORT:3000'
        depends_on:
            - db
        labels:
            - 'com.centurylinklabs.watchtower.enable=true'
        networks:
            - default
            - web
    kusari:
        image: ghcr.io/jurienhamaker/kusari:main
        restart: unless-stopped
        tty: true
        env_file:
            - ./.env
            - ./kusari.env
        environment:
            - 'DATABASE_URL=$KUSARI_DATABASE_URL'
            - 'INVITE_LINK=$KUSARI_INVITE_LINK'
            - 'DISCORD_TOKEN=$KUSARI_DISCORD_TOKEN'
            - 'SENTRY_DNS=$KUSARI_SENTRY_DNS'
            - 'CLIENT_ID=$KUSARI_CLIENT_ID'
            - 'TOP_GG_TOKEN=$KUSARI_TOP_GG_TOKEN'
            - 'TOP_GG_VOTE_LINK=$KUSARI_TOP_GG_VOTE_LINK'
            - 'DISCORDBOTLIST_TOKEN=$KUSARI_DISCORDBOTLIST_TOKEN'
            - 'DISCORDBOTLIST_VOTE_LINK=$KUSARI_DISCORDBOTLIST_VOTE_LINK'
            - 'BOTS_GG_TOKEN=$KUSARI_BOTS_GG_TOKEN'
            - 'BOTS_GG_VOTE_LINK=$KUSARI_BOTS_GG_VOTE_LINK'
        ports:
            - '$EXPOSED_KUSARI_API_PORT:3000'
        depends_on:
            - db
        labels:
            - 'com.centurylinklabs.watchtower.enable=true'
        networks:
            - default
            - web
    db:
        image: postgres:12.2
        environment:
            - 'POSTGRES_USER=$DATABASE_USER'
            - 'POSTGRES_PASSWORD=$DATABASE_PASSWORD'
            - 'POSTGRES_MULTIPLE_DATABASES=$DATABASE_NAME'
        ports:
            - '$EXPOSED_DATABASE_PORT:5432'
        volumes:
            - '$DATA_LOCATION/db:/var/lib/postgresql/data'
            - '$DATA_LOCATION/pg-init-script:/docker-entrypoint-initdb.d/pg-init-scripts.sh'
        networks:
            - default
    pgbackups:
        image: prodrigestivill/postgres-backup-local
        restart: unless-stopped
        volumes:
            - '$DATA_LOCATION/db_backup:/backups'
        depends_on:
            - db
        environment:
            - POSTGRES_HOST=db
            - 'POSTGRES_DB=$DATABASE_NAME'
            - 'POSTGRES_USER=$DATABASE_USER'
            - 'POSTGRES_PASSWORD=$DATABASE_PASSWORD'
            - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
            - SCHEDULE=@every 12h00m00s
            - BACKUP_KEEP_DAYS=7
            - BACKUP_KEEP_WEEKS=4
            - BACKUP_KEEP_MONTHS=6
            - HEALTHCHECK_PORT=81
        networks:
            - default

networks:
    default:
        driver: bridge
    web:
        external: true
