-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "guildSaves" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "highscore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "maxGuildSaves" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Player" ADD COLUMN     "saves" INTEGER NOT NULL DEFAULT 0;
