apiVersion: v2
name: hachimitsu
description: Helm chart for the hachimitsu Discord bot
type: application
version: 0.1.17
appVersion: "main"
dependencies:
  - name: common
    version: "0.1.17"
    repository: "file://../common"
  - name: postgresql
    version: "18.8.5"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
