apiVersion: v2
name: iro
description: Helm chart for the iro Discord hex-color bot (stateless)
type: application
version: 0.1.15
appVersion: "main"
dependencies:
  - name: common
    version: "0.1.15"
    repository: "file://../common"
