apiVersion: v2
name: iro
description: Helm chart for the iro Discord hex-color bot (stateless)
type: application
version: 0.1.8
appVersion: "main"
dependencies:
  - name: common
    version: "0.1.8"
    repository: "file://../common"
