apiVersion: v2
name: kusari
description: Helm chart for the kusari Discord word-chain bot
type: application
version: 0.1.7
appVersion: "main"
dependencies:
  - name: common
    version: "0.1.7"
    repository: "file://../common"
  - name: postgresql
    version: "18.8.5"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: valkey
    version: "6.2.5"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
