apiVersion: v2
name: hoshi
description: Helm chart for the hoshi Discord starboard bot
type: application
version: 0.1.15
appVersion: "main"
dependencies:
  - name: common
    version: "0.1.15"
    repository: "file://../common"
  - name: postgresql
    version: "18.8.5"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
