name: 'Lint: Affected'

on:
  workflow_call:

env:
  NX_NO_CLOUD: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      # - run: yarn nx format:check
      - run: yarn nx affected -t lint
